let tentang = [
    `Saya adalah seorang fresh graduate dari STMIK AMIKBANDUNG yang memiliki semangat tinggi dalam belajar hal baru, motivasi yang tinggi terhadap pekerjaan (growth mindset) dan memiliki atitude yang baik. Berpengalaman dibidang nya selama 4 tahun di 3 perusahaan teknologi dengan berperan sebagai web developer khususnya dibagian backend programmer dengan menggunakan bahasa pemrograman & framework PHP (Laravel) & JavaScript (JQuery, dll).`,
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    `Saya seorang lulusan S1 Teknik Informatika fokus menjadi web developer khususnya backend developer selama 3 tahun yang familiar menggunakan framework PHP (Laravel) seperti membangun Restfull API Menggunakan Sanctum/JWT Token Auth, ataupun Monolith sistem, PostgreSQL/MySQL & Postman. Namun belakangan ini saya hampir menguasai tech stack Javascript selama 1 tahun yang digunakan untuk pengembangan frontend developer seperti NodeJS/Express/VueJS. sehingga memiliki keahlian dasar sebagai Fullstack Developer Junior`,
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    `Saya merupakan lulusan S1 dengan gelar dalam bidang Teknik Informatika dan memiliki IPK sebesar 3.43, mencerminkan pencapaian akademik yang sangat memuaskan. Dengan pengalaman kerja selama 1-3 tahun sebagai web developer, saya telah mendalami pengembangan aplikasi berbasis web dengan fokus utama pada PHP (Laravel) dan Javascript (NodeJS/ExpressJS/VueJS).`,
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    `Selain keahlian teknis, saya dikenal memiliki sikap yang positif dan semangat yang tinggi terhadap pekerjaan. Saya juga cepat dalam mempelajari hal-hal baru dan saya terus memiliki motivasi untuk pertumbuhan pribadi dan profesional. Dengan kombinasi kualifikasi akademik dan pengalaman praktis, saya siap untuk membawa kontribusi berarti dalam dunia pengembangan web dan menjadi aset berharga bagi setiap tim atau individu untuk perusahaan.
    `,
];